name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  biome-checks:
    name: Run biome checks  (format, lint and import sorting)
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: âš¡ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ” Format & Lint
        run: npm run biome:ci
  

  typecheck:
    needs: biome-checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 23]
    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: âš¡ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ” Type Checking (tsc)
        run: npm run typecheck

      - name: ğŸ› ï¸ Are The Types Wrong?
        run: npm run attw


  tests:
    needs: typecheck
    name: Run tests and coverage on ${{ matrix.os }} with Node.js ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20, 22, 23]

    steps: #github says theres a yml error here and its an invalid file??!!
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: âš¡ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ§ª Run Tests with Coverage
        run: npm run test
